### ISSUE TITLE
Gives an error.

### ISSUE THREAD

**Issue by genito66666** [forairan/Ogar#107]
Using Windows 8.1 Update 1.

    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\evgeni\Downloads\Ogar-master\Ogar-master\src\GameServer.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
 
Node.JS is installed.

**Comment by TheMaskedMonkey** [comment]
npm install ws

**Comment by subv3rsion** [comment]
Dependencies must be installed, as mentioned by @TheMaskedMonkey.
You should be able to do `npm install` from the game server directory, which will install all necessary modules.

See: https://github.com/forairan/Ogar#obtaining-and-using
