### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by sayginburak** [forairan/Ogar#28]
I cloned the repo and installed dependencies. when i type "node Ogar --master --game 0" to run the servers. It gives this error. how can I solve this?

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/sayginburak/Documents/Sites/Ogar/Ogar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by vram4** [comment]
The proper command is "node index.js --game 0". The master server doesnt work very well at the moment, so you'll have to leave that out.

**Comment by sayginburak** [comment]
I tried it, it gives also this error.
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by vram4** [comment]
A EACCES error means youre having trouble listening to your port. Try running it with root privileges.

**Comment by sayginburak** [comment]
Thnaks, this worked.
"sudo node index.js --game 0"
